---
apiVersion: v1
kind: Secret
metadata:
  name: tencentcloud-cloud-controller-manager-config
  namespace: kube-system
data:
  # 需要注意的是,secret 的 value 需要进行 base64 编码
  #   echo -n "<REGION>" | base64
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_REGION: "<REGION>"
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_ID: "<SECRET_ID>"
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_KEY: "<SECRET_KEY>"
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_CLUSTER_ROUTE_TABLE: "<CLUSTER_NETWORK_ROUTE_TABLE_NAME>"
  TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_VPC_ID: "<VPC_ID>"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tencentcloud-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: tencentcloud-cloud-controller-manager
    spec:
      dnsPolicy: Default
      tolerations:
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/network-unavailable"
          value: "true"
          effect: "NoSchedule"
      containers:
        - image: ccr.ccs.tencentyun.com/library/tencentcloud-cloud-controller-manager:1.0.1
          name: tencentcloud-cloud-controller-manager
          command:
            - /bin/tencentcloud-cloud-controller-manager
            - --cloud-provider=tencentcloud # 指定 cloud provider 为 tencentcloud
            - --allocate-node-cidrs=true # 指定 cloud provider 为 tencentcloud 为 node 分配 cidr
            - --cluster-cidr=192.168.0.0/20 # 集群 pod 所在网络，需要提前创建
            - --master=<KUBERNETES_MASTER_INSECURE_ENDPOINT> # master 的非 https api 地址
            - --configure-cloud-routes=true
            - --allow-untagged-cloud=true
            - --node-monitor-period=60s
            - --route-reconciliation-period=60s
          env:
            - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_REGION
              valueFrom:
                secretKeyRef:
                  name: tencentcloud-cloud-controller-manager-config
                  key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_REGION
            - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: tencentcloud-cloud-controller-manager-config
                  key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_ID
            - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tencentcloud-cloud-controller-manager-config
                  key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_SECRET_KEY
            - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_CLUSTER_ROUTE_TABLE
              valueFrom:
                secretKeyRef:
                  name: tencentcloud-cloud-controller-manager-config
                  key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_CLUSTER_ROUTE_TABLE
            - name: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_VPC_ID
              valueFrom:
                secretKeyRef:
                  name: tencentcloud-cloud-controller-manager-config
                  key: TENCENTCLOUD_CLOUD_CONTROLLER_MANAGER_VPC_ID
---