---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/tencentcloud-loadbalancer-kind: classic
    service.beta.kubernetes.io/tencentcloud-loadbalancer-type: public
  name: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
